# Generated by Django 5.1.2 on 2024-11-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=15)),
                ('release_date', models.DateField(null=True)),
            ],
            options={
                'ordering': ['name', 'brand'],
            },
        ),
    ]
